### ISSUE TITLE
No longer compiles

### ISSUE THREAD

**Issue by Spiritdude** [vitalif/sophia-perl#1]
Did you recently try to build it? It no longer compiles . . . I built it while ago successful (edit: I used the cpan module covering 0.9), and now tried to update (edit: assuming this covers the most recent sophia), here one of the many error messages:

In file included from /usr/lib/x86_64-linux-gnu/perl/5.20/CORE/perl.h:5089:0,
                 from Sophia.xs:4:
Sophia.xs: In function ‘XS_Database__Sophia__Ctl_set’:
Sophia.xs:162:21: error: too many arguments to function ‘sp_set’
   RETVAL = newSViv( sp_set(ctl->ptr, (void *)key_c, (void *)value_c ) );

---- the sophia-master/sophia.h says:
SP_API int      sp_set(void_, void_);

---- the sophia-master/sophia.c says:
SP_API int      sp_set(void_, void_);
[...]
SP_API int sp_set(void *ptr, void *v)
{
   so *o = sp_cast(ptr, **FUNCTION**);
   if (ssunlikely(o->i->set == NULL)) {
      sp_unsupported(o, **FUNCTION**);
      return -1;
   }
   [...]

**Comment by vitalif** [comment]
It's basically because sophia API was changed in 1.2.3...
It builds with 1.2.2. Just changed the master branch to refer to 1.2.2 tarball instead of master.
Although it should be easy to adapt the new API...
